services:
  - type: web
    name: tamagotchi-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python index.py
    envVars:
      - key: PG_HOST
        sync: false
      - key: PG_USER
        sync: false
      - key: PG_PASSWORD
        sync: false
      - key: PG_DATABASE
        sync: false
